### ISSUE TITLE
Android replacement

### ISSUE THREAD

**Issue by mori-honest** [cyndibaby905/TwitterCover#17]
Is there a library like this for android?

**Comment by cyndibaby905** [comment]
Good question! As far as I know,  there isn't. But I'd like to reimplement it in android soon:)

**Comment by mori-honest** [comment]
I already made [a stackOverFlow question](http://stackoverflow.com/questions/30323569/implement-twitter-cover-parallaxblur-effect-on-imageview?noredirect=1#comment48744371_30323569) and [found this](https://github.com/Frank-Zhu/PullZoomView) without blur support.
If you can add blur to that lib and make a pull request.

**Comment by cyndibaby905** [comment]
The [Android version](https://github.com/cyndibaby905/TwitterCover-Android) is also available now.

**Comment by Morteza-Rastgoo** [comment]
Thank you!
great work!
if it is possible add new effects to it.
