### ISSUE TITLE
NSKVODeallocate

### ISSUE THREAD

**Issue by Alkalouti** [cyndibaby905/TwitterCover#19]
Fatal Exception: NSInternalInconsistencyException
An instance 0x12f8d9400 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x17404da70> ( <NSKeyValueObservance 0x1702c54e0: Observer: 0x0, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17024ae00> <NSKeyValueObservance 0x1702c8030: Observer: 0x0, Key path: contentSize, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17024afb0> )

I have this issues replied in crashlytics all the crashes in iOS 8 i add removeTwitterCoverView at dealloc.
any suggest idea 
Thanks,

**Comment by cyndibaby905** [comment]
Take a look at the [README.md](https://github.com/cyndibaby905/TwitterCover/blob/master/README.md), you should remove it in your dealloc method, otherwise memory leaks:

```
[scrollView removeTwitterCoverView];  
```

**Comment by Alkalouti** [comment]
@cyndibaby905 Thanks for your replay 
I'm already add it into dealloc

**Comment by cyndibaby905** [comment]
Does the crash still occur after you added the remove code?

**Comment by Alkalouti** [comment]
Yes i add the remove TwitterCoverView from the beginning, should that happened becouse i add it into slider menu

**Comment by cyndibaby905** [comment]
Set two breakpoint on your `dealloc` method: one before the remove code and another after. Then print its `observationInfo` to see what happened.

BTW, does the function performed on main thread? This is a point.

**Comment by Alkalouti** [comment]
I add the breakpoint in viewWillDisappear, because the dealloc not called the slider menu will never dealloc.
the observer return  0x187002cb4 <+108>: adrp   x8, 58946.

no I add the function direct on viewdidload.

**Comment by cyndibaby905** [comment]
I mean,  does this function

```
[scrollView removeTwitterCoverView];
```

perform on main thread?

**Comment by Alkalouti** [comment]
Sorry i miss understand you,
No it's not work on main thread

**Comment by cyndibaby905** [comment]
Just make the call on main thread.

**Comment by Alkalouti** [comment]
ok thanks
